package com.viralground.backend.logging;

public enum AuditAction {
    MEMBER_LOGIN,
    MEMBER_LOGOUT,
    MEMBER_PASSWORD_RESET,
    MEMBER_SIGNUP,
    MEMBER_WITHDRAWN,
    MEMBER_STATUS_CHANGED,
    MARKETING_CONSENT_CHANGED,
    CAMPAIGN_APPLIED,
    CAMPAIGN_STATE_CHANGED,
    CONTENT_SUBMITTED,
    REVIEW_CREATED,
    FILE_PRESIGNED,
    FILE_UPLOADED,
    CONTACT_RECEIVED,
    PROFILE_CHANGED,
    METRICS_UPDATED,
    METRICS_SYNC_TRIGGERED,
    PAYMENT_STATE_CHANGED,
    SOCIAL_ACCOUNT_CONNECTED,
    SOCIAL_ACCOUNT_DISCONNECTED
}
